apiVersion: v1
kind: Service
metadata:
  name: {{ include "mock-helm-push.fullname" . }}
  labels:
    {{- include "mock-helm-push.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mock-helm-push.selectorLabels" . | nindent 4 }}
